#!/usr/sbin/nft -f
flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;
        iif "lo" accept
        ct state established,related accept
        ct state invalid drop
        ip protocol icmp icmp type { echo-request, echo-reply, destination-unreachable, time-exceeded } limit rate 5/second accept
        ip6 nexthdr icmpv6 icmpv6 type { echo-request, echo-reply, destination-unreachable, time-exceeded, nd-neighbor-solicit, nd-router-advert, nd-neighbor-advert } limit rate 5/second accept
        counter drop
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
        counter drop
    }

    chain output {
        type filter hook output priority 0; policy drop;
        oif "lo" accept
        meta skuid 0 udp dport 5353 accept
        meta skuid 0 tcp dport 9040 accept
        meta skuid 106 tcp dport { 443, 80 } accept
        meta skuid 106 tcp dport 9001 accept
        meta skuid 106 tcp dport 9030 accept
        tcp dport { 9050, 9150, 9040 } accept
        udp dport 5353 accept
        counter drop
    }
}
