#!/bin/sh
# AnonOS MVP - MAC address randomization on network interface up
# Install to /etc/network/if-up.d/mac-randomize

# Only run for physical interfaces (eth*, wlan*, en*, wl*)
case "$IFACE" in
    eth*|wlan*|en*|wl*)
        # Wait for interface to be ready
        sleep 1
        # Bring down, randomize MAC, bring up
        /sbin/ip link set dev "$IFACE" down
        /usr/bin/macchanger -r "$IFACE"
        /sbin/ip link set dev "$IFACE" up
        ;;
    *)
        exit 0
        ;;
esac